// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSwEgL8b2v4gZTH44s3nHObT9f4WL-Yk',
    appId: '1:881758573026:web:c7e13b4a2f0185a07fa9bb',
    messagingSenderId: '881758573026',
    projectId: 'medcine-management-system-007',
    authDomain: 'medcine-management-system-007.firebaseapp.com',
    storageBucket: 'medcine-management-system-007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFVHJhwfPplvA5Qau4mBJbwY8qlKtm0g',
    appId: '1:881758573026:android:4403c8a6959f7afe7fa9bb',
    messagingSenderId: '881758573026',
    projectId: 'medcine-management-system-007',
    storageBucket: 'medcine-management-system-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3l3LlNGfOo0X3ka2cU9lm2821MISpH2k',
    appId: '1:881758573026:ios:ed26eaa2641f3c077fa9bb',
    messagingSenderId: '881758573026',
    projectId: 'medcine-management-system-007',
    storageBucket: 'medcine-management-system-007.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyManagementSystemFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3l3LlNGfOo0X3ka2cU9lm2821MISpH2k',
    appId: '1:881758573026:ios:ed26eaa2641f3c077fa9bb',
    messagingSenderId: '881758573026',
    projectId: 'medcine-management-system-007',
    storageBucket: 'medcine-management-system-007.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyManagementSystemFlutter',
  );
}
